[package]
name = "qemu_fuzzer"
version = "0.10.0"
edition = "2021"

[dependencies]
libafl = "0.11.1"
libafl_bolts = "0.11.1"
libafl_qemu = { version = "0.11.1", features = ["x86_64", "usermode"] }
env_logger = "0.10"
