[package]
name = "inproc_fuzzer"
version = "0.10.0"
edition = "2021"
build = "build.rs"

[dependencies]
libafl = "0.11.1"
libafl_bolts = "0.11.1"
libafl_targets = { version = "0.11.1", features = ["sancov_pcguard_edges", "libfuzzer"] }
env_logger = "0.10"
